awx_version: 22.4.0

awx_image_name: wp-awx
awx_base_image_mirrored_from: "ghcr.io/ansible/awx:{{ awx_version }}"
awx_base_image_mirrored_to: "docker-registry.default.svc:5000/wwp-test/awx:{{ awx_version }}"
awx_image_full_name: "docker-registry.default.svc:5000/{{ ansible_oc_namespace }}/wp-awx:{{awx_version}}"

awx_verbose: true

awx_receptor_version: v1.4.1
awx_receptor_image_name: wp-receptor
awx_receptor_image_full_name: "docker-registry.default.svc:5000/{{ ansible_oc_namespace }}/{{ awx_receptor_image_name }}:{{ awx_receptor_version }}"
# The following path is fixed by AWX (see
# https://github.com/ansible/awx/blob/devel/awx/main/tasks/receptor.py#L640):
awx_receptor_socket_path: /var/run/receptor/receptor.sock

# AWX will spin up pods using this image when it has work to do.
# 💡 Here “ee” means “execution environment”, not “enterprise edition”.
awx_ee_version: "{{ awx_version }}"
awx_ee_image_mirrored_from: "ghcr.io/ansible/awx-ee:{{ awx_ee_version }}"
awx_ee_image_mirrored_to: "docker-registry.default.svc:5000/wwp-test/awx-ee:{{ awx_ee_version }}"
awx_ee_image_full_name: "docker-registry.default.svc:5000/{{ ansible_oc_namespace }}/ee:{{ awx_ee_version }}"

awx_web_hostnames:
  wwp: awx-wwp.epfl.ch
  wwp-test: awx-poc-vpsi.epfl.ch
  wwp-infra: awx-wwp-infra.epfl.ch

awx_redis_image_mirrored_from: redis:6.0
awx_redis_image_mirrored_to: "docker-registry.default.svc:5000/{{ ansible_oc_namespace }}/redis:6.0"

awx_inventory: "{{ awx_inventories[ansible_oc_namespace] }}"
awx_inventories:
  wwp: prod
  wwp-test: test

awx_service_account: awx

# `curl` (and therefore) `dnf` and `yum` are broken on CentOS 9 +
# OpenShift 3.11, but only during builds ☹
# (https://github.com/moby/moby/issues/42680). Here is a workaround:
shellmacro_poor_mans_curl: >-
       pip3 install requests >&2 &&
       python3 -c 'import requests; import sys; sys.stdout.buffer.write(requests.get(url = sys.argv[-1]).content)' --

awx_organization_name: "WWP"
awx_project_name: "wp-ops"
awx_project_github_url: "https://github.com/epfl-si/wp-ops"

awx_inventory_source_path: "ansible/inventory/wordpress-instances.py"
awx_inventory_source_name: "{{ awx_inventory_source_path | basename }}"
awx_inventory_name: "WordPress instances"

awx_selfk8s_credential_name: "oc wwp-test K8S bearer token"

awx_template_jobs_slice_count: 10
awx_template_jobs_playbook: "ansible/playbooks/wordpress-main.yml"
awx_template_jobs_verbosity: 0

# The namespace we build in (and consume build images from).
# ../tasks/k8s-build.yml is only applied in this namespace.
awx_build_namespace: wwp-test

# The UID and GID to use when running tasks such as wp-cli, creating files on NFS etc.
awx_unix_credentials:
  uid: 33
  gid: 33
  user: www-data
  group: www-data
