# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible/ansible-deps-cache/bin/eyaml edit -d \
#     --pkcs7-public-key ansible/eyaml/epfl_wp_test.pem \
#     ansible/roles/awx-instance/vars/secrets-wwp-test.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

# We use the same database as the production instance.
awx_postgresql_database:
  name: awx-wwp
  host: pg-test-exopge.epfl.ch
  port: 5432
  user: awx-wwp
  password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAAiKlOEHzLsqgq6wFEc0cOUH+h3b3heDkufIXyoM3YYfg+1b1hBW2aL9xLWcTaVGBCGLhMdrz5tIlgpa2haVIIHLFrWD01l0281Kq5/M1k8obeuyshpE5AU8f5zQX/DSGCwLXkO+9VlTX67cebY0dzl8B+ZiEyPIQf4fFARu/DlPpPNBFXrtphyLewIzM0zXES0EFM9NdjcZ9CmKsUEtT5z1Ai7+8E7ZXTZaXENeaEABZK4np4NU9kUkIcVFJ33Rn23kvHS2kdXtU1GJKkMOAUVgiUO4/UehQPcMVfI0kcCL50UHeQLDsa+3FzMNnf36j5R425iUS4GYBn7rm7QKvHTBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBnZSKInpBncI+roi2EkrgxgCDGQLOO4B5V33M1Ir1UYbGTlokqltrhMwMAwmFP2Ri3VQ==]
# This key is used to encrypt/decrypt things in the database; likewise, it must be the same as the test instance.
django_secret_key: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAjT9M33ENrqKS4G/mpGoMt/KQxs7XQEeZu383mhAjoXYRaSGj9kA0XsqkQJYmJHkQt8cs/mmRWb4JlY1z0ZUXBCBRmc//3ibeqlGpSz4p5Vi3/gbL/4k22zpHHORwl83L4nDdsjr9z9uJuoyv5pOjcbiwcPKrhGv5Vclp6XAFjWLR5o5n2q3XO5ObEzb16p9xrC15r0en4GZzMe57uFxqYN6iOSablP+5LK+c2/ompA54LMzVyfBwTqo6hpBBDaT+jaJpZCage/bJJafW+x3TP0pEcb6zb5YMVi0rhyXBN4Nl3OvDL6dL1Wl30w4ql07g3WYpTYE1xzrNX96VLoEvsTBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDAG8MScdUZSsbLgj4yEGQXgCCJipFRCwUg6S9v38Gt9okES2RtoWYxhgqm/7zeacruug==]

awx_admin_password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAfHGrEG6EUQaCI81PlSIKCd27mtkaAkiDUrprp3rGOQKav5eUZBOfckna+1mUBb4JBCiQg3MpmsH8yB9m1i9cpYxyPhYp6cXv3k460Mi3bfhH8eBLJf7ktMyiL6ER5JU79nmlNDFh9vjZJuLwlQLaGZtEPdDiDyDomHmdsuyYneq4qJK2T2IFzwJDbDYUVZpC73L1yGWxUTFWeFbGZEP0Z7iKQP0CvR5YgicTqSG17QM5Jwb0tOyzPhKODgnSnl6KUrq1ELoZ/NS7TrY9dgJcaJCK5iwMwCxH0xOB3XGACHu9BRlm/aYa8Zc5FUGcaT7eUbc8pXDXTmcfagy61o68fjBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCESyCSwKnKP9J4GZqhFSLKgCCAq5gh85pVk5vHH+FivxGRkqdNIxdVlfSa7igQBrT/Ww==]

awx_ldap_credentials:
  bind_dn: cn=awx-poc-os-wwp,ou=services,o=epfl,c=ch
  bind_password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAGqfoF+ra4Or3ZdRl4UUJjjBEQwdm8nwQX+DvSNBS5OwbmKKox7nMq1Foh/LrDAMF/L1JbDAxphzSdU9gcOjzd9Ntc77DmEnyMitQmZfpdowd44/5UI/9go3kqeO41e/hCJ8RBDJilXlCJY+J52lLNsCv34Jb0GXcVnHmUdoXLNqRAkgOZrw7V6R8FHHSB2ePTBTs9zydCzVq7Kmf12raL0GG9Bpm0No/aC11JmWoFQnHU9FmhP8Z77RM4b7P0Jyz1+t5dI/pFXSpku1jHYbTGHVvdKxzELdVMSuRm4+WbZq1N1YU+l5wWJ8SigMbBAGurEacq5HU73Yp5Hfvgf+5dDBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBC/XMVFCMm1YOEGtYhtC3S4gCBGXod7BSlm6wqRrUCQBqMiblbaxD1T4g9g0mDCnSWJeQ==]

awx_notifications:
  email:
    address: idev-fsd-monitoring@epfl.ch
    username: idev-fsd-monitoring
    password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAHPQJb2uUSo+j2TRyP/3SMJXPmhP1mXPk1dKXKGxcx1e9ruU/CC294FwpuBuJV087Z6BLaZz6w3d+FPchOcHBBJ0VBw9cREnm3McnaRBF6FFY1G66583GJxrExixsc7129DK/yorJtw3H7zcg3iGLxaBK8truqqkMAgDZnrX/4GH5/RXy+1UIY2mfFEaDnJHrBSCIz+JDQqKprBcrr4sk7jAu8+3MsuYbnoQoZgP4i5YufJvmhLcLYXU5sDWr1EZju/hz1y+LRmNbdKJGhCIPmt0pjpYmetc0ASY8JzEPzA5ozXbuqXN6KU1uq5S4Vl7NVPT71qIlOPazKJRPM7re0TBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAQgPG4Epby2yhwhfBOxc/vgCD8V3nSaFSYLOTgUq93SXkGfwoKHFjz1Not2EHKjMSHpw==]

wp-veritas:
  mongodb:
    host: test-mongodb-svc-1.epfl.ch
    database: wp-veritas-test
    user: wp-veritas-test
    password: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAaUBG7ot04jLHTmc7NV8uy2Db/S8g+Q5MKjg13z93nFewf39U/vieMKml8oxVmZzlfDdmEjfvPRcgH/GZDMtDE29GwKKH2HyWM4UxnxA9mjzncDFfDrYt8UTk4Fut6021Ia9NJCkJyKzLWCfMWyknHlBxYUwriMUl2PCfajqDx0rzqeVZjU5BLFa6KF1om+hCv2Al1iRV/OWf5uUpIHOv9Oj9MkfcEf1+0Zudvm3vxlk34IEKH1AVuKh31+jM2FqFAW84ZtKaW4s39/S+sTriMOmNCIN0BHjjUzs2bSdxYJJBAMjdXW5XsihTiOVogl7KF2d4yAgyhk/Hnjtvkw+WezBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB2p4DRflIrvTw1amCzhHG6gDCKwJY4Clqbm/zxagUdGeksMn1y3ACT69oExonH2OOt5dJ/uU3f/3+aPtdpctqh/GU=]
  accred:
    password: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAHgHmZTclJMYAYyRBYnLolaUvUlyrrmSNHfxwub5pn32KHMQstqOzCXf24rNQWJTgf3cZLWwPX1fOKtlc8A+mwWZSU2lOBHSlv6U6CSef/1T6nUe3FLucniINQPsH0uetXID2bCHPg9qzw59jiWrt5CIhmnXFLUxNt1Z3GES244ab49+75vRFOCELBJvcKECSr0LwfIWekkbyGEw5GgJGscqMQkA1Fw9rvf/ibqCBhgPArzWlOb0xWUUQbcz5NAhAnXPd4igjuZ/sJZwT+9UCiSmJTj+i68ku3Xyfe49nM4DNWx+bYF7g0RRGw8k+j+f8W1FaJn3/rsi81VpReKuw6DA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAhMGU+jyrBhImppwinwFjlgBC0RQ31ces1EArRPbrwS238]
  telegram:
    bot_token: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAaWVuKHK3tSrzW0ewaa130eua0m+tTFavA5MV4IOV+EZcbef3YK2gj/kEqYdGtbEKwCxpfcQ7HS4QCdempN3MQgOSvPN0TlWYRbqiD1pP48vXV+cVyOFiBT8q0L8tdaguSVNad1NXdyPa/Kr+S5WShNVF4W7yI8aCoueXjXuvd0yxBLp12z2ahmb2E/fWufQCco4vCNC3uaY+nNVmO7H9fKoglp4Lyrw7DY7xCulb6bqJl9bEtAdMJGBdUkyHOBDDe810YVXwZ/YnxnAJ9wDqhX8763yFe4rZohNgU7JRT+12sphrrwwihtIGLEt/t/CgeSeG5s3Cg6MvNcb5LgZo1TBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCcgDMBVAYhy5qRq/06n/3kgDBK92Fjkhd8UoiYxXkvPxJ9tG0NavlYxXpwY2au3TDGUWMJy0qOg3/TnsDoObdLNsQ=]
    recipient_ids:
      # To obtain the Telegram ID of a person, forward one of its messages to @userinfobot
      # To obtain the Telegram ID of a group, see https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id
      # - 9917772       # Nicolas Borboën
      # - 159096082     # Grégory Charmier
      # - 1395659114    # ???
      - 124636020     # Dominique Quatravaux
      # - -368232882    # wp-veritas updates
  awx_client:
    token: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAX8srt9CHhlVpnH2vL30vu1O1cBXDD5ZnFyiIji6Pp7t3/1LBcv2YnM4w9aiB3e+hgZGaiRdKgEJAXV54SOtrvFBJzXeL2TTwPZcILKaN1xeK2r9QK5hjRiCx5MB7XRYyEXlFvkRbEOwtyDk+YoHQRlqqHnaq93rlBwqj3tNnDhi3UP3QF21Ze0OZuokzeryehNCusJIP5ulQy3/NnK0lJhsfdtdGo9Dhs2TweVkZHH59kFe+rjpVbjP35z8k5Vl1H65dIKXDoQVqiO5NkVVnoqYIsvqer54Fbpl0Ha4k0LiZEbnux3VFaUtnevEbo/uvPbvHaOh+iDPLTcwIRI9bFjBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAIjsu0OPu2jnbMgZAsQV7YgCAt0xl/hF0aIY/8+uEVVj7FwJHYWGqm/yfcVlLMPDolpA==]
