- tags: always
  include_vars: ../../wordpress-namespace/vars/image-vars.yml

- name: Clinic image
  include_tasks:
    file: _buildconfig.yml
    apply:
      tags:
      - wp.build
      - wp.build.clinic
      - wp.clinic
  tags:
  - wp.build
  - wp.build.clinic
  - wp.build.clinic.rebuild
  - wp.clinic
  - wp.clinic.rebuild
  vars:
    buildconfig_name: clinic
    buildconfig_description: Image with git, jq, bash etc. for build-related tasks
    buildconfig_base: "{{ ansible_quay_hostname }}/{{ quay_organization }}/wp-php:{{ nginx_deployment_images_tag }}"
    buildconfig_source:
      dockerfile: |
        FROM {{ ansible_quay_hostname }}/{{ quay_organization }}/wp-php:{{ nginx_deployment_images_tag }}
        RUN touch /wp/clinic-marker \
            && echo date -Iseconds > /wp/clinic-marker
        # Install some conveniance tools
        RUN apt-get update \
            && apt-get install -y --no-install-recommends \
                bash \
                ca-certificates \
                curl \
                dnsutils \
                file \
                git \
                htop \
                iputils-ping \
                jq \
                less \
                lsof \
                tcpdump \
                traceroute \
                vim \
                wget \
            && rm -rf /var/lib/apt/lists/*
        # Chmod the WordPress volume
        RUN chmod a+rwX -R /wp

    buildconfig_rebuild_tags:
    - wp.build.clinic.rebuild
    - wp.clinic.rebuild
