- tags: always
  include_vars: "{{ item }}"
  with_items:
    - build-vars.yml
    - quay-vars.yml

# Required for quay-vars.yml, above:
- tags: always
  include_vars:
    file: ../../../vars/quay-secrets.yml
    name: quay_credentials

- name: Mirror images used to build `FROM`
  include_tasks:
    file: mirrors.yml
    apply:
      tags:
        - wp.build
        - wp.build.mirrors
  tags:
    - wp.build
    - wp.build.mirrors

- name: WP-Clinic Builder
  include_tasks:
    file: clinic.yml
    apply:
      tags:
      - wp.build
      - wp.build.clinic
      - wp.clinic
  tags:
    - wp.build
    - wp.build.clinic
    - wp.build.clinic.rebuild
    - wp.clinic
    - wp.clinic.rebuild

- name: wp-base/Tekton
  include_tasks:
    file: tekton.yml
    apply:
      tags:
        - wp.build
        - wp.tekton
        - wp.build.tekton
  tags:
    - wp.build
    - wp.tekton
    - wp.build.tekton
    - wp.tekton.pipeline
    - wp.build.tekton.pipeline

- name: Kong reverse proxy for blue/green(/red/yellow/orange) testing
  include_tasks:
    file: continuous-integration.yml
    apply:
      tags:
        - wp.build
        - wp.build.kong
  tags:
        - wp.build
        - wp.build.kong
        - wp.build.kong.rebuild
        - wp.build.kong.restart

- name: GitHub continuous integration poller / webhook
  include_tasks:
    file: continuous-integration.yml
    apply:
      tags:
        - wp.ci
        - wp.build
        - wp.build.ci
        - wp.continuous-integration
  tags:
        - wp.ci
        - wp.build
        - wp.build.ci
        - wp.build.ci.rebuild
        - wp.build.ci.restart
        - wp.continuous-integration
        - wp.continuous-integration.rebuild
        - wp.continuous-integration.restart

- name: Fruit deployments
  include_tasks:
    file: kong.yml
    apply:
      tags:
        - wp.kong
        - wp.kong.configuration
  tags:
    - wp.kong
    - wp.kong.configuration
    - wp.kong.deployments

- name: Prometheus Exporter for Python
  include_tasks:
    file: prometheus-exporter-with-python.yml
    apply:
      tags:
        - wp.prometheus-exporter-with-python
  tags:
    - wp.prometheus-exporter-with-python
