- tags: always
  include_vars: "{{ item }}"
  with_items:
    - ../../vars/quay-vars.yml

- name: "Mirror the Ubuntu images we use as base"
  include_tasks:
    file: _mirror.yml
  vars:
    mirror_name: ubuntu
    mirror_from: "docker.io/library/ubuntu"
    mirror_tags: ["noble", "latest", "jammy"]

- name: "Mirror the Python 3.13 base images"
  include_tasks:
    file: _mirror.yml
  vars:
    mirror_name: python
    mirror_from: "docker.io/library/python"
    mirror_tags: ["3.13-slim", "3.13-trixie"]

- name: "Mirror the composer image"
  include_tasks:
    file: _mirror.yml
  vars:
    mirror_name: composer
    mirror_from: "docker.io/library/composer"
    mirror_tags: ["2.9"]
