- name: "`tekton` ServiceAccount - Answers webhooks, starts `PipelineRun`s"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: tekton
        namespace: "{{ inventory_namespace }}"

- name: "Role for the `tekton` ServiceAccount"
  kubernetes.core.k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: tekton
        namespace: "{{ inventory_namespace }}"
      rules:
        - apiGroups: ["tekton.dev"]
          resources: ["pipelineruns"]
          verbs: ["create", "get", "list", "patch"]

- name: "RoleBinding for the `tekton` ServiceAccount"
  kubernetes.core.k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: tekton
        namespace: "{{ inventory_namespace }}"
      subjects:
        - kind: ServiceAccount
          name: tekton
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: tekton

- name: "Mirror {{ tekton_handyman_image.original }} to Quay"
  epfl_si.quay.quay_repository:
    organization: "{{ tekton_handyman_image_mirrored.organization }}"
    name: "{{ tekton_handyman_image_mirrored.shortname }}"
    description: "Mirrored from {{ _mirrored_from_short }}"
    visibility: public
    mirror:
      from: "{{ _mirrored_from_short }}"
      robot_account: "{{ quay_mirror_robot_account }}"
      tags:
      - '{{ tekton_handyman_image.original | split(":") | last }}'
  vars:
    _mirrored_from_short: >-
      {{ tekton_handyman_image.original | split(":") | first }}

- name: "Tekton storage"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: nfs.epfl.ch/v1alpha1
      kind: NfsSubdirProvisioner
      metadata:
        name: "wordpress-build"
        namespace: "{{ inventory_namespace }}"
      spec:
        nfs:
          server: "{{ storage_nas[inventory_deployment_stage].nfs_server }}"
          path:  "{{ storage_nas[inventory_deployment_stage].path }}/wordpress-build"
        storageClass:
          defaultClass: false
          name: "wordpress-nfs-build"
        resources:
          requests:
            cpu: 50m
