- name: "Mirror {{ tekton_handyman_image.original }} to Quay"
  epfl_si.quay.quay_repository:
    organization: "{{ tekton_handyman_image_mirrored.organization }}"
    name: "{{ tekton_handyman_image_mirrored.shortname }}"
    description: "Mirrored from {{ _mirrored_from_short }}"
    visibility: public
    mirror:
      from: "{{ _mirrored_from_short }}"
      robot_account: "{{ quay_mirror_robot_account }}"
      tags:
      - '{{ tekton_handyman_image.original | split(":") | last }}'
  vars:
    _mirrored_from_short: >-
      {{ tekton_handyman_image.original | split(":") | first }}
