- name: "`ConfigMap/tekton-scripts`"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: tekton-scripts
        namespace: "{{ inventory_namespace }}"
        labels:
          app: tekton-webhook
      data:
        wp-base-webhook.py: >-
          {{ lookup("template", "wp-base-webhook.py") }}

- name: "`Secret/quay-credentials`"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: quay-credentials
        namespace: "{{ inventory_namespace }}"
      type: Opaque
      stringData:
        QUAY_API_HOSTNAME: "{{ ansible_quay_hostname }}"
        QUAY_API_BEARER_TOKEN: "{{ ansible_quay_bearer_token }}"

- epfl_si.quay.robot_account_permission:
    robot_account_name: "{{ quay_puller_robot_account_name }}"
    organization: "{{ tekton_handyman_image_mirrored.organization }}"
    repository_name: "{{ tekton_handyman_image_mirrored.shortname }}"
    permission: read

- name: "`Deployment/tekton-webhook`"
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tekton-webhook
        namespace: "{{ inventory_namespace }}"
        labels:
          app: tekton-webhook
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: tekton-webhook
        template:
          metadata:
            labels:
              app: tekton-webhook
          spec:
            containers:
              - name: webhook-handler
                image: "{{ tekton_handyman_image.mirrored }}"
                envFrom:
                  - secretRef:
                      name: quay-credentials
                ports:
                  - name: tekton-webhook
                    containerPort: 8080
                command: [ "python3", "/tekton-scripts/wp-base-webhook.py" ]
                volumeMounts:
                  - name: tekton-scripts
                    mountPath: /tekton-scripts
                resources:
                  requests:
                    cpu: '{{ _request_cpu }}'
            volumes:
              - name: tekton-scripts
                configMap:
                  name: tekton-scripts
            imagePullSecrets:
              - name: "{{ quay_puller_secret_name }}"
  vars:
    _request_cpu: "100m"

- name: "`Service/tekton-webhook`"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: tekton-webhook
        namespace: "{{ inventory_namespace }}"
        labels:
          app: tekton-webhook
      spec:
        type: ClusterIP
        selector:
          app: tekton-webhook
        ports:
        - name: tekton-webhook
          port: 8080
          protocol: TCP
          targetPort: 8080

- name: "`Route/tekton-webhook`"
  kubernetes.core.k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: tekton-webhook
        namespace: "{{ inventory_namespace }}"
        labels:
          app: tekton-webhook
          route: public
      spec:
        host: "{{ webhook_destination_hostname }}"
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect
        to:
          kind: Service
          name: tekton-webhook
        port:
          targetPort: tekton-webhook

- name: "Tekton tasks required for building"
  kubernetes.core.k8s:
    namespace:  "{{ inventory_namespace }}"
    src: "{{ item }}"
  with_items:
  - https://api.hub.tekton.dev/v1/resource/tekton/task/git-clone/0.9/raw
  - https://github.com/openshift-pipelines/tektoncd-catalog/raw/p/tasks/task-buildah/0.6.0/task-buildah.yaml

- name: "Pipeline/wp-base"
  kubernetes.core.k8s:
    definition:
      apiVersion: tekton.dev/v1
      kind: Pipeline
      metadata:
        name: wp-base
        namespace: "{{ inventory_namespace }}"
      spec:
        params:
          - name: quay-repo
            description: The hostname of the Quay repository to push to
            default: "{{ ansible_quay_hostname }}"
          - name: next-build-id
            description: "Sequence number of the next build to push to Quay"
        workspaces:
          - name: shared-workspace
          - name: dockerconfig
        tasks:
          - name: git-clone
            taskRef:
              kind: Task
              name: git-clone
            params:
              - name: url
                value: https://github.com/epfl-si/wp-ops
            workspaces:
            - name: output
              workspace: shared-workspace
          # TODO: substitute FROM lines with `sed(1)`
          - name: build
            runAfter: [git-clone]
            taskRef:
              kind: Task
              name: buildah
            params:
              - name: IMAGE
                value: "$(params.quay-repo)/{{ quay_organization }}/wp-base:2025-$(params.next-build-id)"
              - name: CONTEXT
                value: "docker/wp-base"
              - name: VERBOSE
                value: "true"
              # TODO: consume AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY out of some Secret and pass them as `--build-arg`s
            workspaces:
            - name: source
              workspace: shared-workspace
