# Ansible playbook for the EPFL WordPress stack

- name: Initial checks
  hosts: all
  gather_facts: no    # Ansible facts are useless for this play
  tasks:
    - name: Check Ansible version
      run_once: true
      assert:
        that: "ansible_version.full is version_compare('2.6', '>=')"
        msg: |
          You must update Ansible to at least 2.6 to use this playbook.

## TODO: restore ability for operator to run things on WordPress sites directly.
## This requires splitting the role so that the `backup`, `restore` and `wipe`
## tasks have a home outside of the operator.
# - name: WordPress sites
#   hosts: |
#     {%- if (ansible_run_tags |
#                           any_known_tag((playbook_dir | dirname) +
#                                         "/roles/wordpress-instance")) -%}
#     {# Note: we are twisting the Ansible concept of “hosts” in this play.
#      # An inventory entry in the all_wordpresses group is a WordPress
#      # instance, rather than a host in the “traditional” sysadmin sense.
#      #}
#     all_wordpresses
#     {%- else -%}
#     {# If no relevant tags are in use (including the implicit "all" tag when -t is not
#      # present on the command line), skip the whole role and save a big chunk of time:
#      #}
#     !all
#     {%- endif -%}
#   gather_facts: no    # Ansible facts are useless for this play
#   roles:
#     - role: ../roles/wordpress-instance

- name: TKGI namespaces
  # Like above, members of the all_tkgi_namespaces are TKGI
  # namespaces, rather than hosts
  hosts: all_tkgi_namespaces
  gather_facts: no    # Ansible facts are useless for this play
  roles:
    - role: ../roles/wordpress-tkgi-namespace

- name: Ansible Tower (AWX) instances
  hosts: awx_instances
  gather_facts: no    # Ansible facts are useless for this play
  roles:
    - role: ../roles/awx-instance
