- include_vars: ../../../vars/image-vars.yml
  tags: always

- include_vars: awx-vars.yml
  tags: always

- name: "Pull upstream awx image into {{ awx_base_image_mirrored_to }}"
  openshift_imagestream:
    metadata:
      name: awx
      namespace: "{{ ansible_oc_namespace }}"
    from: "{{ awx_base_image_mirrored_from }}"
    tag: "{{ awx_version }}"

- name: "Patch {{ awx_base_image_mirrored_to }} into {{ awx_image_name }}"
  register: _awx_buildconfig
  openshift_imagestream:
    tag: "{{ awx_version }}"
    metadata:
      name: "{{ awx_image_name }}"
      namespace: "{{ ansible_oc_namespace }}"
    dockerfile: |
       FROM {{ awx_base_image_mirrored_to }}

       USER 0
       {% if awx_remote_debug is defined %}
       {# Support for pydevd remote debugging - NOT RECOMMENDED for
        # production!
        #
        # Run Ansible with `-e awx_remote_debug=some-hostname-or-IP`
        # to enable this. (Replace `some-hostname-or-IP` with the
        # hostname or IP address of the relay VM, as described below.)
        #
        # You will need to be able to listen on port 12477 from a
        # predictable IP address. The working¹ way to achieve that is
        # as follows:
        #
        # 1. Select some VM in a suitable microsegmentation zone, that
        # you enjoy root privileges on
        #
        # 2. Make sure that its `/etc/ssh/sshd_config` file contains
        # the line
        #
        #       GatewayPorts clientspecified
        #
        # If not, edit that file so that it does, then issue the command
        #
        #       sudo service sshd restart
        #
        # 3. Connect to the VM with reverse port-forwarding enabled, e.g.
        #
        #       ssh -R 0.0.0.0:12477:127.0.0.1:12477 myvm
        #
        # ¹ If you insist on the not-working approach, which
        # admittedly appears to be quite popular, take a look at
        # https://github.com/omrikiei/ktunnel (and also
        # https://github.com/omrikiei/ktunnel/pull/95 - Don't say I
        # didn't warn you.)
        #}
       RUN /var/lib/awx/venv/awx/bin/pip3 install pydevd-pycharm~=231.9161.38
       # As you can see below, setting up a breakpoint is a breeze (not):
       RUN sed -i -e '369a\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ import pydevd_pycharm; pydevd_pycharm.settrace("{{ awx_remote_debug }}", port=12477, stdoutToServer=True, stderrToServer=True)' /var/lib/awx/venv/awx/lib/python3.9/site-packages/awx/main/models/jobs.py
       {% endif %}

       USER 1000
  tags: awx.build.awx
  notify: Restart AWX pod

- name: "Rebuild {{ awx_image_name }} now"
  when: _awx_buildconfig.changed | default(True)
  shell: "oc -n {{ awx_build_namespace }} start-build --wait {{ awx_image_name }}"
  tags: awx.build.awx

- name: "Patch {{ awx_base_image_mirrored_to }} into {{ awx_receptor_image_name }}"
  register: _awx_receptor_buildconfig
  openshift_imagestream:
    tag: "{{ awx_receptor_version }}"
    metadata:
      name: "{{ awx_receptor_image_name }}"
      namespace: "{{ ansible_oc_namespace }}"
    dockerfile: |
       FROM {{ awx_base_image_mirrored_to }}

       USER 0
       RUN pip3 install ansible ansible-runner
       RUN set -e -x; \
          {{ shellmacro_poor_mans_curl }} $({{ shellmacro_poor_mans_curl }} https://api.github.com/repos/ansible/receptor/releases \
            | python3 -c \
              "import sys; import json; import re; \
               release = (r for r in json.load(sys.stdin) if r['name'] == '{{ awx_receptor_version }}').__next__(); \
               asset = (a for a in release['assets'] if re.search('linux_amd64\.tar\.gz$', a['name'])).__next__(); \
               print(asset['browser_download_url'])") \
          | tar -C/usr/local/bin -zxvv receptor
       USER 1000

  tags: awx.build.receptor
  notify: Restart AWX pod

- name: "Rebuild {{ awx_receptor_image_name }} now"
  when: _awx_receptor_buildconfig.changed | default(True)
  shell: "oc -n {{ awx_build_namespace }} start-build --wait {{ awx_receptor_image_name }}"
  tags: awx.build.receptor

- name: "Pull upstream awx-ee image into {{ awx_ee_image_mirrored_to }}"
  openshift_imagestream:
    metadata:
      name: awx-ee
      namespace: "{{ ansible_oc_namespace }}"
    from: "{{ awx_ee_image_mirrored_from }}"
    tag: "{{ awx_version }}"
