#!/usr/bin/python3

from wp_inventory import WPInventory
import json

targets = [{ 
            'ssh_port': '32222',
            'ssh_user': 'www-data',
            'ssh_host': 'ssh-wwp.epfl.ch',
            'remote_path': '/srv/*/*/htdocs'
            }]
prune_elements = {'name': ['wp-*', '.git', '*packages', 'ansible-backup-*'] }
env_prefix = 'prod'

inventory = WPInventory(targets, prune_elements, env_prefix)

print(json.dumps(inventory.get_inventory(), sort_keys=True, indent=4))
