#!/usr/bin/python

import subprocess

pod_name = subprocess.check_output('oc get pods -o name |grep mgmt | cut -d "/" -f2', shell=True)

print ("""all-wordpresses:
  children:
    - wordpress_instances_test_blue
wordpress_instances_test_blue:
  hosts:
    - site1
    - site2
    - site3
  vars:
    ansible_python_interpreter: python3
    ansible_connection: oc
    ansible_oc_namespace: wwp-int
    ansible_oc_pod: %(pod_name)s
    ansible_become: true
    ansible_become_user: www-data
    ansible_become_method: su
_meta:
      hostvars:
        site1:
          name: site1
          bkp: _srv_www_www.epfl.ch_htdocs_research
          domain: foot
        site2:
          name: site2
          bkp: _srv_www_www.epfl.ch_htdocs_research_awards
          domain: foot
        site3:
          name: site3
          bkp: _srv_www_www.epfl.ch_htdocs_research_collaborate
          domain: basket
""" % {"pod_name": pod_name})