# Deploy the Kubernetes operator that manages sites onto TKGI
- tags: always
  include_vars: operator-vars.yml

- name: '`{{ harbor_robot_pull_secret_name }}` Secret in {{ operator_namespace }} namespace'
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ harbor_robot_pull_secret_name }}'
        namespace: '{{ operator_namespace }}'
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ _docker_cfg | to_json | b64encode }}'
  vars:
    _auth: >-
      {{ operator_harbor_secrets.login }}:{{ operator_harbor_secrets.password }}
    _docker_cfg:
      auths:
        vsissp-harbor-p.epfl.ch:
          username: '{{ operator_harbor_secrets.login }}'
          password: '{{ operator_harbor_secrets.password }}'
          auth: '{{ _auth | b64encode }}'

- name: '`WordpressSite` custom resource definition (CRD)'
  kubernetes.core.k8s:
    definition: >-
      {{ lookup('template', 'custom-resource-definition.yaml')
      | from_yaml }}

- name: Kubernetes objects to run the operator
  kubernetes.core.k8s:
    definition: "{{ item }}"
  with_items: >-
      {{ lookup('template', 'operator-wordpress-site.yaml')
      | from_yaml_all }}
