# Deploy the Kubernetes operator that manages sites onto TKGI
- tags: always
  include_vars: operator-vars.yml

- name: Kubernetes objects for the operator
  kubernetes.core.k8s:
    definition: "{{ item }}"
  with_items: "{{ operator_k8s_definitions }}"
