# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible/ansible-deps-cache/bin/eyaml edit -d \
#     --pkcs7-public-key ansible/eyaml/epfl_wp_test.pem \
#     ansible/roles/wordpress-builds/vars/build-secrets.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: "/keybase/team/epfl_wp_test/eyaml-privkey.pem"
  pub: "{{ playbook_dir }}/eyaml/epfl_wp_test.pem"

build:
  s3_assets:
    endpoint_url: https://s3.epfl.ch/
    region: us-east-1
    bucket_name: svc0041-c1561ba80625465c2a53f01693922e7c
    # This is a read-only key. See
    # the Makefile at the root of wp-ops for write
    # access
    key_id: BEK17WIFI2F896UOXHXW
    secret: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAGJl8T1aQuXckHS6TqQ370RbryFada2GaSljnbwM7NOQIk1BrJRxpADttDcNz6cCq/1H/zfHwTgi5FONhqg1pPlDqprS1M8Z+uBAt6r7sLoNlk1qEqtmVeIkHSvjegl5a/wL2oPxXyxtiR6dkfSP8m/q+hlvO41gA3snNALFkOYTG0VGsZj5I8ZDW3nGsQMZCkyka9dzwaRd4kaT1qIqdeU4R2+esim6QCkRexoc0y3gyW+/u7OH3eemTRarF21FrR3fDZo5wnseVeKc+/3oZOK1SpEfUhsddtIGdR5VQQFJzs4nFHF3+0s6jY0I4yj/sYKCo0AYvJQwiPaK6F5SMojBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDUezlAMH9BoHd7XAEvg0pvgDA1kx9xRAUpuYGGQv5h6LabqFzRYryerGcSHpnG5qbbEt6HdM+tA0t1OxA3G8SUhtU=]

github:
  webhooks:
    user: domq
    # This token has `admin:repo_hook` and `public_repo` permissions.
    token: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAfWEmqQKczXLdK4rC6Cwtb5KJltpfbsXTyIKfik+dZhW+P4dI6Ox/nbguuykDoCbrycRYh6vMv1d44TYbmctVswb5QSrCm1CxXyWQIdfxnqRnmtcKpurzRppsWTYJB6Ps9BVqI7JPXGfji5kZ6MZSRE6gKn373c24v6uvEarNFAHCSEn3mjXokpfVH7zZrK8+ZS/nyU/ZjSUUwLfYLiJ0NDnu05SimRFUVoKuNwaK9e6dAjDS+kQjJCVAXru75BbaeiVQkSVWh1xpMmhI8Uz14L+GiLhAXbhWIvR6D6Rg4yPI1oeuXTwbmOJtAfP0CAOebpZBf6AiwXIwPPHPG96lmjBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBoQNS8HU1DsjlzwGqt0/tqgDD3U5UdGp5yhoLhkUSnCjpaq3QLem017CkblQTjaVc3OqHulzwHYwct16zZkvelU7A=]

tekton:
  quay_api:
    # Quay API token that Tekton jobs wield e.g. to create repositories and tags.
    # To regenerate this token:
    # (paraphrased from https://docs.redhat.com/en/documentation/red_hat_quay/3/html-single/red_hat_quay_api_guide/index#token-overview)
    #
    # 1. Browse https://quay-its.epfl.ch/
    # 2. **Make sure to log out and then back in.** Some token manipulation steps require either
    #    that you have a fresh (less than a few minutes old) session, or that you type in your
    #    password to re-autenticate. Unfortunately the latter will *not* work on quay-its.epfl.ch,
    #    no matter what. (Mumble LDAP something something)
    # 3. Browse https://quay-its.epfl.ch/organization/svc0041?tab=applications
    # 4. (If not already done) Create the `tekton-webhook` application. Click the “Create New Application” button in the upper right corner; type in tekton-webhook and press Enter.
    #
    #    💡 If you get prompted for a password at this time, it means that you didn't read
    #    the above instructions carefully. Sorry about that.
    # 5. Click the `tekton-webhook` hyperlink
    # 6. In the left sidebar, click Generate Token (pictured by a cinema ticket)
    # 7. Check the “Administer Repositories”, “Create Repositories” boxes and leave all others unchecked.
    # 8. Click the Generate Access Token button (green) at the bottom
    # 9. Click Authorize application
    # 10. A token should appear. If it doesn't, see 💡, above.
    bearer_token: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEABvh35Hu/5QClS4+czaBe2cPl5nxsyfhSe+CFQTVgS8c66mFqOrRrCEjFfUqpwBOBetl8cyter4WVVbpwgDchDCgX0BOtCm2zCEUq1GB82KLWo9JU3QhqqTj30mG9dNXAEyC3qmVkNMbVuLSaJ1ls79l3AdXNDLSbRfDNWd89RxxcvVEqU1paIc+YMbwb9OXfKQeZzvqxBSU2J3MfSUTcNH+Y1qQjJ4shKy4mbimvAcWXVPo1rd4EJhCdYN7N997O9jd5Ldvs38mCywEnjffZ6m3q6YftyBc3JAEW0Hv5GgRN4S2jOYoTrIu1+d5kRnXiKNcm0aoHJnzIE2G3uxK1nTBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBuPm5ARHXsM/E/p1wf2G65gDA0k2sDV342mgS18iYo72SrOMMxwt8Hy5sXEJ+nPgGKq8ZT4qE6dB7a5tk+kRBPVq8=]
