# This line is used only for local build (docker-compose build).
# When using OpenShift environment, we can configure builds to use an existing image stream
# which is, in our case : wwp/mgmt:prod
FROM jahia2wp_wp-mgmt

USER www-data