apiVersion: wordpress.epfl.ch/v1alpha1
kind: WordpressSite
metadata:
  name: canari
  namespace: wordpress-test
spec:
  hostname: www.epfl.ch
  path: /campus/services/website/canari
  visibility: public
  kubernetes:
    service: www
  wordpress:
    title: Test
    tagline: Canari
    theme: wp-theme-2018
    languages:
      - fr
      - en
    # features:
    #   - Payonline
  epfl:
    unit_id: 13030
history:
  createdBy:
    serviceNow: INC01234567
  comment: |
    Site canari pour tester l'image
