---

- tags:
    - openshift.reverseproxy
  name: Reverse-proxy as a service to OpenShift 3 (during rollover period)
  include_tasks:
    file: "reverseproxy.yml"
    apply:
      tags:
        - openshift.reverseproxy

- tags:
    - openshift.olm
    - openshift.olm.nfs
  name: nfs-subdir-external-provisioner OLM operator instance
  include_tasks:
    file: nfs-ext-olm-user.yml
    apply:
      tags:
        - openshift.olm
        - openshift.olm.nfs
