- include_vars: nfs-vars.yml

- name: NfsSubdirProvisioner object
  kubernetes.core.k8s:
    definition:
      apiVersion: nfs.epfl.ch/v1alpha1
      kind: NfsSubdirProvisioner
      metadata:
        name: "wordpress"
        namespace: "{{ openshift_namespace }}"
      spec:
        nfs:
          server: "{{ nfs_storages[inventory_hostname].server }}"
          path: "{{ nfs_storages[inventory_hostname].path }}"
        storageClass:
          name: "{{ openshift_namespace }}-nfs-subdir"
          defaultClass: false
