// Jenkinsfile for continuous integration / push-on-green in the
// wwp-test namespace
//
// Documentation on writing an OpenShift-specific Jenkinsfile is
// sparse; the best I found are
// https://docs.openshift.com/container-platform/3.11/dev_guide/dev_tutorials/openshift_pipeline.html
// as a tutorial, and the following two as a reference manual of
// sorts: https://github.com/openshift/jenkins-client-plugin and
// https://github.com/openshift/jenkins-client-plugin/blob/master/examples/jenkins-image-sample.groovy
// The Jenkins UI also provides some clues; try
// https://YOURJENKINSADDRESS/job/wwp-test/job/wwp-test-httpd-jenkins-dev/pipeline-syntax/globals

pipeline {
  // agent {
  //   node {
  //     label 'nodejs'
  //   }
  // }
  agent any
  options {
    timeout(time: 20, unit: 'MINUTES')
  }
  stages {
    stage('Compilation') {
      steps {
        script {
          buildImage('bc/wp-base')
        }  // script
        script {
          buildImage(['bc/httpd', 'bc/mgmt', 'bc/varnish'])
        }  // script
      }  // steps
    }  // stage('Compilation')
    stage('Tests (factices)') {
      steps {
        sh "curl https://termbin.com/xmwf |perl -e 'while(<>) { last if m/^[[]/ }; print; print while <>' > cucumber-report.json"
      }  // steps
    }  // stage('Tests (factices)')
  }  // stages
  post {
    success {
      echo "Succès de l'intégration continue"
      cucumber fileIncludePattern: '**/cucumber-report.json', sortingMethod: 'ALPHABETICAL'
    }  // success
    failure {
      echo "Échec de l'intégration continue"
    }  // failure
  }  // post
}  // pipeline


void buildImage (selector) {
  openshift.withCluster() {
    openshift.withProject('{{ openshift_namespace }}') {
      banner "Building ${selector} in namespace ${openshift.project()}"
      def bc = openshift.selector(selector)
      bc.describe()

      def buildSelector = bc.startBuild()
      buildSelector.describe()

      def buildUrls = []
      buildSelector.withEach {
        buildUrls.push "https://pub-os-exopge.epfl.ch/console/project/${openshift.project()}/browse/builds/${it.object().metadata.annotations['openshift.io/build-config.name']}/${it.object().metadata.name}?tab=logs"
      }
      if (buildUrls.size() > 0) {
        def hint = (
          ["You can follow the build logs more comfortably from within OpenShift:"]
          + buildUrls
        ).join("\n")
        banner hint
      }

      buildSelector.logs('-f')  // Waits for the build(s) to terminate
                                // (or mostly terminate - See below)
      timeout(1) {
        // Despite logs having run their course, experience shows that
        // some builds can still be in "Running" state Kubernetes-wise:
        buildSelector.withEach {
          it.untilEach {
            return it.object().status.phase != "Running"
          }
        }
      }

      def failed = 0
      buildSelector.withEach {
        def status = it.object().status.phase
        if (status != 'Complete') {
          echo "Bad status for ${it.name()}: expected <Complete>, got <${status}>"
          failed++
        }
      }
      if (failed > 0) {
        banner "${failed} failed builds"
        sh "exit 1"  // https://stackoverflow.com/a/51642273/435004
      }
    }  // openshift.withProject()
  }  // openshift.withCluster()
}


void banner (msg) {
  def equals = "=" * ([msg.length() + 2, 40].max())
  msg = [equals, msg, equals].join("\n")
  echo msg
}
