# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible/ansible-deps-cache/bin/eyaml edit -d \
#     --pkcs7-public-key ansible/eyaml/epfl_wp_test.pem \
#     ansible/roles/wordpress-namespace/vars/build-secrets.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: "/keybase/team/epfl_wp_test/eyaml-privkey.pem"
  pub: "{{ playbook_dir }}/eyaml/epfl_wp_test.pem"

app_portal_master_credentials:
  id: 05259600-b473-49b4-8bf8-94ccee0b70e0
  secret: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAFB6y+29B3y4G6Vwf54C7VAPbGPnknUQaIjXoyx3cUmL0Taf4ZUrhnMQvjcLnmAWJfUGesoitp3FRAnSJnG9c7eT4V0GnTXkpq9eSOgN8bzv8viKDl58Da2lxiYiaPpzk98qXY385bvD+yfRiwSk/ga8K6UDa5yJobi/UeNY0HACIGVkF8VDYX7umNbXYU/Vn7AX+OrquOSX2zFmJy9hbBoqaJqK7I9IquDVsZj2rBjG2q8HxtWCxJqu08Wld8EGj4mW5UmN0ZByHtpFRLK0PEWFklwoaeApziwuhUUFCQOKgOoWrlhIC3PXcQRbnU8jkyPEUPgR1k/PSfLnd742nKzBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAs2tmIqoag23wsGkFgDf3MgDBF/2Fz0BJ51jTcHRqv9BR5k6go77hY+XV3uLVPuHNbUwJEhyOQ0HroXQ04J1YvyX0=]
  tenant_id: f6c2556a-c4fb-4ab1-a2c7-9e220df11c43
