# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible/ansible-deps-cache/bin/eyaml edit -d \
#     --pkcs7-public-key ansible/eyaml/epfl_wp_test.pem \
#     ansible/roles/wordpress-namespace/vars/build-secrets.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: "/keybase/team/epfl_wp_prod/eyaml-privkey.pem"
  pub: "{{ playbook_dir }}/eyaml/epfl_wp_prod.pem"

app_portal_master_credentials:
  id: 05259600-b473-49b4-8bf8-94ccee0b70e0
  secret: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEApn2Gc5P5mPy+YTF0Z5wS65EdQZETazqon5QCotuwoFfr7rRDghRUoOQgn8YVnXfqro8dL+5zF+0KD/66g/EwEeUyArBpfHyIJ1D3ON6gdk6mXNG7hIGYzYTmUHoX01Px4V+I5RxUgLD16WwXZDa5gH7+tXUgqzo17YKMKl8xZj3gmpRAxKOubrP0MaRnQEVeSCAfvpkfSrAXDgfGTjSkfh6AXpHQDfdOOhEzx9aX+mmykdSyXDLUR4sElti2QBnSr+QBH4gosQkwNUSTB1v1Eksi2C6kfDIcZteyPrMrHLMP55qjcF3xQSxzs/dbVmJgYypTuaN3Y54FLPKX7AOceTBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCVrG/g1uOUFSNzHQpSMBa8gDCvlcmjt4ppW1M1epi6bL6JyvbZX4Jt7ROTHoip91WCqdtlX0UQ1kP01WorNp9/qWw=]
  tenant_id: f6c2556a-c4fb-4ab1-a2c7-9e220df11c43
