# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible/ansible-deps-cache/bin/eyaml edit -d \
#     --pkcs7-public-key ansible/eyaml/epfl_wp_test.pem \
#     ansible/roles/wordpress-namespace/vars/build-secrets.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: "/keybase/team/epfl_wp_test/eyaml-privkey.pem"
  pub: "{{ playbook_dir }}/eyaml/epfl_wp_test.pem"

wp_observability_secrets:
  id: bfc740ea-f4f1-40fd-a557-3cbf323896a8
  secret: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEARM3MIBnVfcqkLetABoxh+ttiTBcFVvZF80CWlijy97v6cgDtG+vdNOzkT6m9yjdlOPNOOwhaZh6DB9DDCaO+ENkRSxPaYwk3tPR+2XfNdyWU6Pf1BJUGyOUdzhYEKlYc0GzKHRzi5XOeAB+3zXv17shFiEygoqBCFfdjEsSeWtIdrllcRxCRLulhxJy6NYBdEqmR2NUhBUF343kW5NfS5jCPcV+w3h9DJG+CYItijN/lW0pHnF/0+7dZ/vBjuHsRdA4Y/Mo11BWLoi0RsNvDgyzmhFcxg3e8nMwJUpSzzgCrxeD2kR/lTapF0P4/0qHN5WFn5TRVzNxGnO7HOhhh6jBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBHMQfKp2OSVioxa/eONYDkgDDEk8Swnl9Q9nISYuDFY2I1oJ9VFAgBtY9denBpA9NnjBG3PHymR6kza3AhVyvLl/w=]
  tenant_id: f6c2556a-c4fb-4ab1-a2c7-9e220df11c43
