#!/usr/bin/env python3

# USAGE:  ./wordpress-instance [--full]
#           --full : to get all details about each WP instance

import sys
import os
# To be able to include package wp_inventory in parent directory
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from wp_inventory import WPInventory
import json

targets = [{ 
            'ssh_port': '32222',
            'ssh_user': 'www-data',
            'ssh_host': 'test-ssh-wwp.epfl.ch',
            'remote_path': '/srv'
            }]

# Elements to prune while using "find" command to get WordPress instances
prune_elements = { 
                'name': ['wp-*', '.git', '*packages', 'jahia-data', 'ansible-backup-*'],
                'path': ['/srv/lvenries', '/srv/jenkins']
}

env_prefix = 'test'

# Defining if we have to include all details for WP instances
include_details = len(sys.argv)> 1 and sys.argv[1] == '--full'

inventory = WPInventory(targets, prune_elements, env_prefix, include_details=include_details)

print(json.dumps(inventory.get_inventory(), sort_keys=True, indent=4))
