#!/usr/bin/env python3

import sys
import os
# To be able to include package wp_inventory in parent directory
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from wp_inventory import WPInventory
import json

targets = [{ 
            'ssh_port': '32222',
            'ssh_user': 'www-data',
            'ssh_host': 'test-ssh-wwp.epfl.ch',
            'remote_path': '/srv'
            }]

# Elements to prune while using "find" command to get WordPress instances
prune_elements = { 
                'name': ['wp-*', '.git', '*packages', 'jahia-data', 'ansible-backup-*'],
                'path': ['/srv/lvenries', '/srv/jenkins']
}

env_prefix = 'test'

inventory = WPInventory(targets, prune_elements, env_prefix)

print(json.dumps(inventory.get_inventory(), sort_keys=True, indent=4))
