#!/bin/sh
#
# This is a wrapper to ansible-playbook to do or redo all the things.
#
# Usage:
#
# ./ansible/deploy
#
# ./ansible/deploy -l charte-wp-dcsl
#
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

cd "$(dirname "$(realpath "$0")")"

inventories="-i hosts-dev"
# One can override these overrides on the command line
default_flags="-e play_update=yes -e play_backup=yes -e play_create_or_restore=yes"

warn () {
    if [ -n "$1" ]; then
        echo "$@" >&2
    else
        cat >&2
    fi
}

fatal () {
    warn "$@"
    exit 1
}

which keybase >/dev/null || warn <<NO_KEYBASE

WARNING: keybase is not installed, cannot decipher and push secrets.

NO_KEYBASE

which eyaml >/dev/null || warn <<NO_EYAML

WARNING: eyaml is not installed, cannot decipher and push secrets.

NO_EYAML

###########################################################################

while [ -n "$1" ]; do
    case "$1" in
        --prod)
            inventories="$inventories -i hosts-prod"
            shift ;;
        *)
            break ;;
    esac
done

ansible-playbook $default_flags $inventories "$@" playbooks/wordpress-main.yml
