#!/bin/sh
# This is an Ansible playbook to dump sites in the WXR format, and
# recover the spoils to localhost.
#
# Usage:
#
#     ./ansible/dump -e "to=/some/where"
#
# or equivalently
#
#     ./ansible/dump -e "dump_local_dir=/some/where"
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

cd "$(dirname "$(realpath "$0")")"

ansible-playbook -e "play_dump=yes" -e "dump_local_dir={{ to }}" -i hosts-dev "$@" playbooks/wordpress-main.yml
