#!/bin/bash
#
# This is a wrapper around ansible / ansible-playbook.
#
# Usage ("ansible" mode):
#
#   ansible/wpsible -m raw www-wordpresses -a 'echo {{ wp_dir }}'
#
# Usage ("ansible-playbook" mode):
#
#   ansible/wpsible -l charte-wp-dcsl
#
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

cd "$(dirname "$(realpath "$0")")"

# One can override these on the command line
playbook_flags="-e play_update=yes -e play_backup=yes -e play_create_or_restore=yes"
ansible_flags="-e @roles/wordpress-instance/vars/main.yml"

warn () {
    if [ -n "$1" ]; then
        echo "$@" >&2
    else
        cat >&2
    fi
}

fatal () {
    warn "$@"
    exit 1
}

platform_check () {
    test -d /keybase/team || warn <<NO_KEYBASE

WARNING: keybase is not installed, cannot decipher and push secrets.

NO_KEYBASE

    which eyaml >/dev/null || warn <<NO_EYAML

WARNING: eyaml is not installed, cannot decipher and push secrets.

NO_EYAML
}


inventory_mode="test"
inventories () {
    CONFIG=$(oc config current-context)
    if [[ $CONFIG == "myproject/192-168-99-"*"developer" ]]
    then
      echo "-i inventory/minishift -e " IPADRS="`curl https://api.ipify.org`" " "
    elif [[ $CONFIG == "wwp-int/pub-os-exopge-epfl-ch:443/"* ]]
    then
      echo "-i inventory/wp-int "    
    else
	case "$inventory_mode" in
       	    test) echo "-i inventory/test" ;;
	    test_and_prod) echo "-i inventory/test -i inventory/prod" ;;
	    wp_veritas) echo "-i inventory/wp-veritas" ;;
	esac
    fi
}

###########################################################################

mode=ansible-playbook

declare -a ansible_args
while [ "$#" -gt 0 ]; do
  case "$1" in
        --prod)
            inventory_mode="test_and_prod"
            shift ;;
        --wp-veritas)
            inventory_mode="wp_veritas"
            shift ;;
        -m) mode=ansible
            ansible_args+=("-m")
            shift ;; 
        --connector)
            export ANSIBLE_CONNECTION_MODE=$2
            shift 
            shift ;;
        --ssh-port)
            export ANSIBLE_FORWARD_PORT=$2
            oc port-forward $(oc get pods -o name | grep mgmt | head -1) $2:22 &
            export SSH_TUNNEL_PID=$!
            shift
            shift;;
        *)
            ansible_args+=("$1")
            shift ;;
    esac
done

set -e

case "$mode" in
    ansible-playbook)
        platform_check
        ansible-galaxy install -i -r requirements.yml >/dev/null 2>&1
        ansible-playbook $playbook_flags $(inventories) "${ansible_args[@]}" \
                         -e "wpsible_cwd=$OLDPWD" \
                         playbooks/wordpress-main.yml
        ;;
    ansible)
        ansible $(inventories) $ansible_flags "${ansible_args[@]}"
        ;;
esac

if [[ ! -z "${SSH_TUNNEL_PID}" ]]; then 
    kill -9 "$SSH_TUNNEL_PID"
    unset SSH_TUNNEL_PID
fi
