#!/bin/bash
#
# This is a wrapper around ansible / ansible-playbook.
#
# Usage ("ansible" mode):
#
#   ansible/wpsible -m raw all_wordpresses -a 'echo {{ wp_dir }}'
#
# Usage ("ansible-playbook" mode):
#
#   ansible/wpsible -l charte-wp-dcsl
#
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

cd "$(dirname "$0")"; cd "$(/bin/pwd)"

# One can override these on the command line
playbook_flags="-e play_update=yes -e play_backup=yes -e play_create_or_restore=yes"
ansible_flags="-e @roles/wordpress-instance/vars/main.yml"

warn () {
    if [ -n "$1" ]; then
        echo "$@" >&2
    else
        cat >&2
    fi
}

fatal () {
    warn "$@"
    exit 1
}

platform_check () {
    if ! test -f ansible-deps-cache/.versions 2>/dev/null; then
        curl https://raw.githubusercontent.com/epfl-si/ansible.suitcase/master/install.sh | \
            SUITCASE_DIR=$PWD/ansible-deps-cache SUITCASE_ANSIBLE_REQUIREMENTS=requirements.yml \
                        SUITCASE_PIP_EXTRA="requests bcrypt passlib mitogen==0.2.9" \
                        SUITCASE_PYTHON_VERSION="3.8.10" \
                        SUITCASE_ANSIBLE_VERSION="3.4.0" bash -x
    fi
    export PATH="$PWD/ansible-deps-cache/bin:$PATH"
    export ANSIBLE_ROLES_PATH="$PWD/ansible-deps-cache/roles"
    export ANSIBLE_COLLECTIONS_PATHS="$PWD/ansible-deps-cache"

    oc_check
}

oc_check () {
  if ! oc projects >/dev/null 2>&1; then
    echo "Please login to openshift:"
    oc login
  fi
}

inventory_mode="test"
inventories () {
    case "$mode" in
        ansible-playbook)
            echo "-i inventory/lazy-wordpress-instances.yml" ;;
        *)
            echo "-i inventory/wordpress-instances.py" ;;
    esac
    case "$inventory_mode" in
        test) echo "-i inventory/test" ;;
        test_and_prod) echo "-i inventory/test -i inventory/prod" ;;
    esac
}

###########################################################################

export WWP_NAMESPACES=wwp-test

mode=ansible-playbook

declare -a ansible_args
while [ "$#" -gt 0 ]; do
  case "$1" in
        --prod)
            inventory_mode="test_and_prod"
            WWP_NAMESPACES="wwp-test,wwp"
            shift ;;
        --wp-veritas)
            # Ignored for backward compatibility
            shift ;;
        -m) mode=ansible
            ansible_args+=("-m")
            shift ;;
        *)
            ansible_args+=("$1")
            shift ;;
    esac
done

# https://github.com/ansible/ansible/issues/32499, https://bugs.python.org/issue35219
case "$(uname -s)" in
    Darwin) export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ;;
esac

set -e

platform_check
case "$mode" in
    ansible-playbook)
        ansible-playbook $playbook_flags $(inventories) "${ansible_args[@]}" \
                         -e "wpsible_cwd=$OLDPWD" \
                         .interactive-playbooks/main.yml
        ;;
    ansible)
        ansible $(inventories) $ansible_flags "${ansible_args[@]}"
        ;;
esac
