#!/bin/bash
#
# This is a wrapper around ansible / ansible-playbook.
#
# Usage ("ansible" mode):
#
#   ansible/wpsible -m raw all_wordpresses -a 'echo {{ wp_dir }}'
#
# Usage ("ansible-playbook" mode):
#
#   ansible/wpsible -l charte-wp-dcsl
#
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

cd "$(dirname "$0")"; cd "$(/bin/pwd)"

# One can override these on the command line
playbook_flags="-e play_update=yes -e play_backup=yes -e play_create_or_restore=yes"
ansible_flags="-e @roles/wordpress-instance/vars/main.yml"

warn () {
    if [ -n "$1" ]; then
        echo "$@" >&2
    else
        cat >&2
    fi
}

fatal () {
    warn "$@"
    exit 1
}

ensure_ansible () {
    if ! test -f ansible-deps-cache/.versions 2>/dev/null; then
        curl https://raw.githubusercontent.com/epfl-si/ansible.suitcase/master/install.sh | \
            SUITCASE_DIR=$PWD/ansible-deps-cache SUITCASE_ANSIBLE_REQUIREMENTS=requirements.yml \
                        SUITCASE_PIP_EXTRA="requests bcrypt passlib mitogen==0.2.9 docker resolvelib<0.6.0,>=0.5.3 kubernetes" \
                        SUITCASE_WITH_KEYBASE=1 \
                        SUITCASE_WITH_EYAML=1 \
                        SUITCASE_WITH_HELM=1 \
                        SUITCASE_ANSIBLE_VERSION="10.1.0" bash -x
    fi

    . ansible-deps-cache/lib.sh
    ensure_ansible_runtime
}

inventory_mode="test"
inventories () {
    case "$inventory_mode" in
        test) echo "-i inventory/test" ;;
        test_and_prod) echo "-i inventory/test -i inventory/prod" ;;
        prod_only) echo "-i inventory/prod" ;;
        rke2_test) echo "-i inventory/rke2/hosts-test.yml" ;;
    esac
}

###########################################################################


mode=ansible-playbook
playbook="playbook.yml"
declare -a ansible_args
while [ "$#" -gt 0 ]; do
  case "$1" in
        --prod)
            inventory_mode="test_and_prod"
            shift ;;
        --prod-only)
            inventory_mode="prod_only"
            shift ;;
        --wp-veritas)
            # Ignored for backward compatibility
            shift ;;
        --rke2_test)
            # Kept for backward compatibility - Use test inventory
            shift ;;
        --install-only)
            mode=install-only
            shift ;;
        -m) mode=ansible
            ansible_args+=("-m")
            shift ;;
        *)
            ansible_args+=("$1")
            shift ;;
    esac
done

set -e

ensure_ansible
case "$mode" in
    install-only) : ;;
    ansible-playbook)
        ansible-playbook $playbook_flags $(inventories) "${ansible_args[@]}" \
                         -e "wpsible_cwd=$OLDPWD" \
                         $playbook
        ;;
    ansible)
        ansible $(inventories) $ansible_flags "${ansible_args[@]}"
        ;;
esac
