operator_src_dir: "{{ wpsible_ops_dir }}/operator-wordpress-site"

operator_kustomize_config_dir: "{{ operator_src_dir }}/config/default"

operator_k8s_definitions: >-
  {{ lookup('kubernetes.core.kustomize',
  dir=operator_kustomize_config_dir
  ) | from_yaml_all }}
