apiVersion: v1
baseDomain: epfl.ch
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
metadata:
  name: okd-fsd
networking:
  clusterNetwork:
  - cidr: 192.168.0.0/18
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.64.0/18
  networkType: OVNKubernetes
  serviceNetwork:
  - 192.168.128.0/18
platform:
  none: {}
bootstrapInPlace:
  installationDisk: /dev/sda
pullSecret: '{{ lookup("pipe", "keybase fs read " + okd_pull_secret_keybase_file) }}'
sshKey: |
   {{ lookup("url", "https://github.com/domq.keys") }}
   {{ lookup("url", "https://github.com/rosamaggi.keys") }}
   {{ lookup("url", "https://github.com/ponsfrilus.keys") }}
   {{ lookup("url", "https://github.com/lvenries.keys") }}
   {{ lookup("url", "https://github.com/obieler.keys") }}
   {{ lookup("url", "https://github.com/williambelle.keys") }}
   {{ lookup("url", "https://github.com/dragonleman.keys") }}
