apiVersion: v1
baseDomain: epfl.ch
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
metadata:
  name: okd-fsd
networking:
  clusterNetwork:
  - cidr: 192.168.0.0/18
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.64.0/18
  networkType: OVNKubernetes
  serviceNetwork:
  - 192.168.128.0/18
platform:
  none: {}
bootstrapInPlace:
  installationDisk: /dev/sdb
pullSecret: '{{ lookup("pipe", "keybase fs read " + okd_pull_secret_keybase_file) }}'
sshKey: |
    {{ lookup("github_keys", ["domq", "rosamaggi", "ponsfrilus", "lvenries", "obieler", "williambelle", "dragonleman"]) | indent(4) }}
